version: "3"

services:
  lowkey-vault:
    container_name: example-lowkey-vault
    image: nagyesta/lowkey-vault:1.15.0
    ports:
      - "10543:10543"
    volumes:
      - key-import:/import/:ro
    environment:
      LOWKEY_ARGS: "--server.port=10543 --LOWKEY_VAULT_NAMES=- --LOWKEY_DEBUG_REQUEST_LOG=true --LOWKEY_IMPORT_LOCATION=/import/keyvault.json.hbs"
volumes:
  key-import:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "$PWD/local/lowkey-vault/import/"
